name: iOS Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-ios:
    name: Build iOS and Submit to App Store
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Step 3: Enable Corepack for Yarn 4
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.10.3 --activate

      # Step 4: Setup Expo and EAS
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      # Step 5: Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Step 6: Get version tag
      - name: Get version tag
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      # Step 7: Update package.json version
      - name: Update package.json version
        run: |
          VERSION="${{ steps.version.outputs.tag }}"
          # Remove 'v' prefix if present (e.g., v1.0.0 -> 1.0.0)
          VERSION_NUMBER="${VERSION#v}"
          echo "Updating package.json version to $VERSION_NUMBER"

          # Update package.json using Node.js
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            pkg.version = '$VERSION_NUMBER';
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
          "

          echo "✅ package.json updated to version $VERSION_NUMBER"
          cat package.json | grep '"version"'

      # Step 8: Set APP_VERSION environment variable
      - name: Export APP_VERSION for EAS Build
        run: |
          VERSION="${{ steps.version.outputs.tag }}"
          VERSION_NUMBER="${VERSION#v}"
          echo "APP_VERSION=$VERSION_NUMBER" >> $GITHUB_ENV
          echo "✅ APP_VERSION set to $VERSION_NUMBER"

      # Step 9: Build and Submit iOS on EAS
      - name: Build and Submit iOS on EAS
        id: build_ios
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
        run: |
          echo "Building and submitting iOS with version $APP_VERSION..."
          eas build --platform ios --profile production --auto-submit --non-interactive --no-wait --json > ios_build.json
          BUILD_ID=$(cat ios_build.json | jq -r '.[0].id')
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
          echo "🍎 iOS Build ID: $BUILD_ID"
          echo "📱 iOS build will auto-submit to App Store Connect when complete"
          echo "🔗 View iOS build: https://expo.dev/accounts/[your-account]/projects/cherry-studio/builds/$BUILD_ID"

      # Step 10: Create GitHub Release Note
      - name: Create or Update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Cherry Studio ${{ steps.version.outputs.tag }}
          body: |
            ## Cherry Studio ${{ steps.version.outputs.tag }} - iOS

            ### 🍎 iOS
            - Built with EAS Build (production profile)
            - Automatically submitted to App Store Connect
            - **Build ID**: `${{ steps.build_ios.outputs.build_id }}`
            - [View Build Details on Expo](https://expo.dev/accounts/[your-account]/projects/cherry-studio/builds/${{ steps.build_ios.outputs.build_id }})

            ---

            📝 **Note**: iOS build is in progress on EAS. Check the build status link above.

            🤖 Automatically generated by GitHub Actions
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 11: Build Summary
      - name: Build Summary
        if: success()
        run: |
          echo "## Build Started! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🍎 iOS" >> $GITHUB_STEP_SUMMARY
          echo "- **Build ID**: \`${{ steps.build_ios.outputs.build_id }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: 🚀 Building and will auto-submit to App Store Connect" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Details**: [View on Expo](https://expo.dev/accounts/[your-account]/projects/cherry-studio/builds/${{ steps.build_ios.outputs.build_id }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Release" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: \`${{ steps.version.outputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: 📝 Draft created on GitHub" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub Release**: ${{ steps.create_release.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ✅ Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Monitor the build progress on Expo Dashboard" >> $GITHUB_STEP_SUMMARY
          echo "2. Once build completes, it will auto-submit to App Store Connect" >> $GITHUB_STEP_SUMMARY
          echo "3. Review and submit for TestFlight/App Store review in App Store Connect" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "_Note: Replace [your-account] with your Expo account name in the links above_" >> $GITHUB_STEP_SUMMARY

      # Step 12: Build Failure Summary
      - name: Build Failure Summary
        if: failure()
        run: |
          echo "## Build Failed ❌" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The iOS build process encountered an error. Please check the logs above for details." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -n "${{ steps.build_ios.outputs.build_id }}" ]; then
            echo "### 🍎 iOS Build" >> $GITHUB_STEP_SUMMARY
            echo "- **Build ID**: \`${{ steps.build_ios.outputs.build_id }}\`" >> $GITHUB_STEP_SUMMARY
            echo "- **View Details**: [Expo Dashboard](https://expo.dev/accounts/[your-account]/projects/cherry-studio/builds/${{ steps.build_ios.outputs.build_id }})" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi

          echo "### 🔍 Troubleshooting" >> $GITHUB_STEP_SUMMARY
          echo "- Check the [EAS Build documentation](https://docs.expo.dev/build/introduction/)" >> $GITHUB_STEP_SUMMARY
          echo "- Review the build logs on Expo dashboard for detailed error messages" >> $GITHUB_STEP_SUMMARY
          echo "- Ensure all credentials and secrets are properly configured" >> $GITHUB_STEP_SUMMARY
          echo "- Verify App Store Connect API credentials are valid" >> $GITHUB_STEP_SUMMARY
